services:
  base: &base
    container_name: base # Explicitly name the base container
    image: registry.99digital.co.il/online
    pull_policy: if_not_present
    env_file: .env ## Change this file for customized env variables
    volumes:
      - /mnt/app_shared:/app/storage

  rails:
    <<: *base
    container_name: rails # Explicitly name the rails container
      #    depends_on:
      #- postgres
      #- redis
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    container_name: sidekiq # Explicitly name the sidekiq container
      #depends_on:
      #- postgres
      #- redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

